apiVersion: v1
kind: Service
metadata:
  name: webshoppingagg
  namespace: webshoppingagg
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webshoppingagg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshoppingagg
  namespace: webshoppingagg
spec:
  selector:
    matchLabels:
      app: webshoppingagg
  replicas: 2
  template:
    metadata:
      labels:
        app: webshoppingagg
    spec:
      containers:
      - name: webshoppingagg
        image: dataconstruct/sdlc-example-infra-api-gateway-shoppingag:2a1752e290c661ed6c00a8bd2078629e29ac3534
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: urls__basket
          value: "http://basket.basket"
        - name: urls__catalog
          value: "http://catalog.catalog"
        - name: urls__orders
          value: "http://ordering.ordering"
        - name: urls__identity
          value: "http://identity.identity"
        - name: CatalogUrlHC
          value: "http://catalog.catalog/hc"
        - name: OrderingUrlHC
          value: "http://ordering.ordering/hc"
        - name: IdentityUrlHC
          value: "http://identity.identity/hc"
        - name: BasketUrlHC
          value: "http://basket.basket/hc"
        - name: MarketingUrlHC
          value: "http://marketing.marketing/hc"
        - name: PaymentUrlHC
          value: "http://payment.payment/hc"
        - name: LocationUrlHC
          value: "http://locations.locations/hc"