apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: front-end
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 2
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: dataconstruct/sdlc-example-app-front-end:50a9acc919634beb84c21228a35c9c91a9e8bd33
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: PurchaseUrl
          value: "http://webshoppingapigw.webshoppingapigw"
        - name: IdentityUrl
          value: "http://eshop-identity.YOUR_HOST_HERE.com"
        - name: MarketingUrl
          value: "http://webmarketingapigw.webmarketingapigw"
        - name: SignalrHubUrl
          value: "http://ordering-signalhub.ordering-signalhub"
        - name: IdentityUrlHC
          value: "http://identity.identity/hc"
        - name: PurchaseUrlHC
          value: "http://webshoppingapigw.webshoppingapigw/hc"
        - name: MarketingUrlHC
          value: "http://webmarketingapigw.webmarketingapigw/hc"
        - name: UseCustomizationData
          value: "True"
        - name: UseLoadTest
          value: "False"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-end
  namespace: front-end
  annotations:  
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: eshop.YOUR_HOST_HERE.com
    http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80