apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: catalog
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 2
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: dataconstruct/sdlc-example-app-catalog:6418328fcb9fac9b59c09b8303c031281d94d24f
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:80"
        - name: ConnectionString
          value: "Server=sql-data.common-infra;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word"
        - name: EventBusConnection
          value: "rabbitmq.common-infra"
        - name: AzureServiceBusEnabled
          value: "False"
        - name: UseCustomizationData
          value: "True"
        - name: AzureServiceBusEnabled
          value: "False"
        - name: AzureStorageEnabled
          value: "False"
        - name: Touch
          value: "1"
        - name: PicBaseUrl
          value: "http://eshop-webshoppingapigw.YOUR_HOST_HERE.com/api/v1/c/catalog/items/[0]/pic/"