apiVersion: v1
kind: Service
metadata:
  name: nosql-data
  namespace: common-infra
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: nosql-data
---
apiVersion: v1
kind: Pod
metadata:
  name: nosql-data
  namespace: common-infra
  labels:
    app: nosql-data
spec:
  containers:
  - name: nosql-data
    image: mongo
    ports:
    - containerPort: 27017