apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: common-infra
spec:
  ports:
  - name: http
    port: 15672
    targetPort: 15672
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  namespace: common-infra
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
    - containerPort: 15672
    - containerPort: 5672