apiVersion: v1
kind: Service
metadata:
  name: redis-data
  namespace: common-infra
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-data
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-data
  namespace: common-infra
  labels:
    app: redis-data
spec:
  containers:
  - name: redis-data
    image: redis:alpine
    ports:
    - containerPort: 6379